name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Setup files
      env: 
        SSHDOG_PORT: ${{ secrets.SSHDOG_PORT }}
        CHISEL_ADDR: ${{ secrets.CHISEL_ADDR }}
        CHISEL_CRED: ${{ secrets.CHISEL_CRED }}
        CHISEL_LOCAL_PORT: ${{ secrets.CHISEL_LOCAL_PORT }}
        CHISEL_REMOTE_PORT: ${{ secrets.CHISEL_REMOTE_PORT }}
        SSHD_USER: ${{ secrets.SSHD_USER }}
        SSHD_PASS: ${{ secrets.SSHD_PASS }}
        SSHD_KEY: ${{ secrets.SSHD_KEY }}
      run: |
        sudo mkdir -p /var/run/sshd
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        echo "TCPKeepAlive yes" | sudo tee -a /etc/ssh/sshd_config
        sudo usermod -aG sudo runner
        echo "runner:$SSHD_PASS" | sudo chpasswd
        sudo mkdir "/home/runner/.ssh"
        echo $SSHD_KEY | sudo tee "/home/runner/.ssh/authorized_keys"
        echo 'runner ALL=(ALL:ALL) NOPASSWD:ALL' | sudo EDITOR='tee -a' visudo
        sudo service ssh restart
        curl -L https://storage.googleapis.com/addic7ed-subs.appspot.com/ffmpeg-N-102633-g3da8758144-svt-hevc.tar.gz | sudo tar -xvz -C /usr/bin
        curl -OL https://downloads.rclone.org/v1.55.1/rclone-v1.55.1-linux-amd64.deb && sudo dpkg -i rclone-*.deb && rm rclone-*.deb
        curl -o chisel.gz -L https://github.com/jpillora/chisel/releases/download/v1.7.6/chisel_1.7.6_linux_amd64.gz && gzip -d chisel.gz && chmod +x chisel && sudo mv chisel /usr/bin
        chisel client --keepalive 5s --auth $CHISEL_CRED $CHISEL_ADDR R:$CHISEL_REMOTE_PORT:localhost:$CHISEL_LOCAL_PORT