name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Setup files
      env: 
        SSHD_PORT: ${{ secrets.SSHD_PORT }}
        CHISEL_ADDR: ${{ secrets.CHISEL_ADDR }}
        CHISEL_CRED: ${{ secrets.CHISEL_CRED }}
        CHISEL_LOCAL_PORT: ${{ secrets.CHISEL_LOCAL_PORT }}
        CHISEL_REMOTE_PORT: ${{ secrets.CHISEL_REMOTE_PORT }}
        SSHD_USER: ${{ secrets.SSHD_USER }}
        SSHD_PASS: ${{ secrets.SSHD_PASS }}
      run: |
        sudo apt update && sudo apt -y install openssh-server
        curl -o chisel.gz -L https://github.com/jpillora/chisel/releases/download/v1.7.6/chisel_1.7.6_linux_amd64.gz && gzip -d chisel.gz && chmod +x chisel && sudo mv chisel /usr/bin
        chisel client --keepalive 5s --auth $CHISEL_CRED $CHISEL_ADDR R:$CHISEL_REMOTE_PORT:localhost:$CHISEL_LOCAL_PORT
