name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Setup files
      env: 
        SSHD_PORT: ${{ secrets.SSHD_PORT }}
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        CHISEL_LOCAL_PORT: ${{ secrets.CHISEL_LOCAL_PORT }}
        SSHD_USER: ${{ secrets.SSHD_USER }}
        SSHD_PASS: ${{ secrets.SSHD_PASS }}
        SSHD_KEY: ${{ secrets.SSHD_KEY }}
      run: |
        sudo mkdir -p /var/run/sshd
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        echo "TCPKeepAlive yes" | sudo tee -a /etc/ssh/sshd_config
        sudo adduser $SSHD_USER --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
        sudo usermod -aG sudo $SSHD_USER
        echo "$SSHD_USER:$SSHD_PASS" | sudo chpasswd
        sudo mkdir "/home/${SSHD_USER}/.ssh"
        echo $SSHD_KEY | sudo tee "/home/${SSHD_USER}/.ssh/authorized_keys"
        sudo service ssh restart
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get remove -y '^ghc-8.*'
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet/
        curl -L https://storage.googleapis.com/addic7ed-subs.appspot.com/ffmpeg-libsvthevc-x265-linux64.tar.gz | sudo tar -xvz -C /usr/bin
        curl -OL https://downloads.rclone.org/v1.55.1/rclone-v1.55.1-linux-amd64.deb && sudo dpkg -i rclone-*.deb && rm rclone-*.deb
        curl -o ngrok.zip -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok.zip && sudo mv ngrok /usr/bin
        ngrok authtoken $NGROK_AUTH_TOKEN
        ngrok tcp $CHISEL_LOCAL_PORT > /dev/null 2>&1
