name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Setup files
      env: 
        SSHD_PORT: ${{ secrets.SSHD_PORT }}
        CHISEL_ADDR: ${{ secrets.CHISEL_ADDR }}
        CHISEL_CRED: ${{ secrets.CHISEL_CRED }}
        CHISEL_LOCAL_PORT: ${{ secrets.CHISEL_LOCAL_PORT }}
        CHISEL_REMOTE_PORT: ${{ secrets.CHISEL_REMOTE_PORT }}
        SSHD_USER: ${{ secrets.SSHD_USER }}
        SSHD_PASS: ${{ secrets.SSHD_PASS }}
      run: |
        sudo mkdir -p /var/run/sshd
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        echo "TCPKeepAlive yes" | sudo tee -a /etc/ssh/sshd_config
        sudo adduser $SSHD_USER --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
        sudo usermod -aG sudo $SSHD_USER
        echo "$SSHD_USER:$SSHD_PASS" | sudo chpasswd
        sudo service ssh restart
        curl -L https://storage.googleapis.com/addic7ed-subs.appspot.com/ffmpeg-release-amd64-static.tar.xz | tar -xvJ && sudo mv ffmpeg-* /opt/ffmpeg
        curl -OL https://downloads.rclone.org/v1.55.1/rclone-v1.55.1-linux-amd64.deb && sudo dpkg -i rclone-*.deb && rm rclone-*.deb
        curl -o chisel.gz -L https://github.com/jpillora/chisel/releases/download/v1.7.6/chisel_1.7.6_linux_amd64.gz && gzip -d chisel.gz && chmod +x chisel && sudo mv chisel /usr/bin
        chisel client --keepalive 5s --auth $CHISEL_CRED $CHISEL_ADDR R:$CHISEL_REMOTE_PORT:localhost:$CHISEL_LOCAL_PORT
